In [1]:
import numpy as np
import pandas as pd
import torch
torch.set_printoptions(edgeitems=2, threshold=50, linewidth=75)

# смотрим на данные в пандасе

In [2]:
ddf = pd.read_csv('data/bike-sharing-dataset/hour-fixed.csv', sep=',')
ddf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17520 entries, 0 to 17519
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     17520 non-null  int64  
 1   dteday      17520 non-null  object 
 2   season      17520 non-null  int64  
 3   yr          17520 non-null  int64  
 4   mnth        17520 non-null  int64  
 5   hr          17520 non-null  int64  
 6   holiday     17520 non-null  int64  
 7   weekday     17520 non-null  int64  
 8   workingday  17520 non-null  int64  
 9   weathersit  17520 non-null  int64  
 10  temp        17520 non-null  float64
 11  atemp       17520 non-null  float64
 12  hum         17520 non-null  float64
 13  windspeed   17520 non-null  float64
 14  casual      17520 non-null  int64  
 15  registered  17520 non-null  int64  
 16  cnt         17520 non-null  int64  
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB


In [3]:
ddf

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
0            1  2011-01-01       1   0     1   0        0        6   
1            2  2011-01-01       1   0     1   1        0        6   
2            3  2011-01-01       1   0     1   2        0        6   
3            4  2011-01-01       1   0     1   3        0        6   
4            5  2011-01-01       1   0     1   4        0        6   
...        ...         ...     ...  ..   ...  ..      ...      ...   
17515    17375  2012-12-31       1   1    12  19        0        1   
17516    17376  2012-12-31       1   1    12  20        0        1   
17517    17377  2012-12-31       1   1    12  21        0        1   
17518    17378  2012-12-31       1   1    12  22        0        1   
17519    17379  2012-12-31       1   1    12  23        0        1   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
0               0           1  0.24  0.2879  0.81     0.0000       3   
1               0           1  0.22  0.2727  0.80     0.0000       8   
2               0           1  0.22  0.2727  0.80     0.0000       5   
3               0           1  0.24  0.2879  0.75     0.0000       3   
4               0           1  0.24  0.2879  0.75     0.0000       0   
...           ...         ...   ...     ...   ...        ...     ...   
17515           1           2  0.26  0.2576  0.60     0.1642      11   
17516           1           2  0.26  0.2576  0.60     0.1642       8   
17517           1           1  0.26  0.2576  0.60     0.1642       7   
17518           1           1  0.26  0.2727  0.56     0.1343      13   
17519           1           1  0.26  0.2727  0.65     0.1343      12   

       registered  cnt  
0              13   16  
1              32   40  
2              27   32  
3              10   13  
4               1    1  
...           ...  ...  
17515         108  119  
17516          81   89  
17517          83   90  
17518          48   61  
17519          37   49  

[17520 rows x 17 columns]

In [4]:
ddf.describe()

instant        season            yr          mnth            hr  \
count  17520.000000  17520.000000  17520.000000  17520.000000  17520.000000   
mean    8652.180023      2.494521      0.500000      6.515068     11.500000   
std     5036.025134      1.109442      0.500014      3.449604      6.922384   
min        1.000000      1.000000      0.000000      1.000000      0.000000   
25%     4286.750000      2.000000      0.000000      4.000000      5.750000   
50%     8645.500000      2.500000      0.500000      7.000000     11.500000   
75%    13015.250000      3.000000      1.000000     10.000000     17.250000   
max    17379.000000      4.000000      1.000000     12.000000     23.000000   

            holiday       weekday    workingday    weathersit          temp  \
count  17520.000000  17520.000000  17520.000000  17520.000000  17520.000000   
mean       0.028767      2.999258      0.683562      1.429224      0.495291   
std        0.167156      2.004034      0.465099      0.642868      0.193208   
min        0.000000      0.000000      0.000000      1.000000      0.020000   
25%        0.000000      1.000000      0.000000      1.000000      0.340000   
50%        0.000000      3.000000      1.000000      1.000000      0.500000   
75%        0.000000      5.000000      1.000000      2.000000      0.660000   
max        1.000000      6.000000      1.000000      4.000000      1.000000   

              atemp           hum     windspeed        casual    registered  \
count  17520.000000  17520.000000  17520.000000  17520.000000  17520.000000   
mean       0.474215      0.628025      0.190663     35.395205    152.620205   
std        0.172492      0.193071      0.122946     49.205358    151.304840   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.333300      0.480000      0.104500      4.000000     32.000000   
50%        0.484800      0.630000      0.194000     16.000000    114.000000   
75%        0.621200      0.790000      0.253700     48.000000    219.000000   
max        1.000000      1.000000      0.850700    367.000000    886.000000   

                cnt  
count  17520.000000  
mean     187.938299  
std      181.447622  
min        0.000000  
25%       38.000000  
50%      140.000000  
75%      280.000000  
max      977.000000

# считываем данные в нампи, и не меняя хранилища создаем объект тензора

In [5]:
bikes_numpy = np.loadtxt(
    "data/bike-sharing-dataset/hour-fixed.csv", 
    dtype=np.float32, 
    delimiter=",", 
    skiprows=1, 
    converters={1: lambda x: float(x[8:10])})              # сразу вычленяет порядковый номер дня в месяце 

In [6]:
bikes = torch.from_numpy(bikes_numpy)

In [7]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

# далее, зная, что данные уже упорядочены и пропуски заполнены нулевыми арендами, выделяем отдельное измерение под сутки: Дни - Каналы - Часы (N-C-L)

In [8]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
daily_bikes.shape, daily_bikes.stride()            # N-L-C

(torch.Size([730, 24, 17]), (408, 17, 1))

In [9]:
daily_bikes = daily_bikes.transpose(1, 2)
daily_bikes.shape, daily_bikes.stride()            # N-C-L

(torch.Size([730, 17, 24]), (408, 1, 17))

**NB!:** при вызове метода `view` на тензоре возвращает новый тензор с другими размерностью и шагами без изменения хранилища. 
Это позволяет перегруппировывать тензор практически без затрат, поскольку никакие данные копировать не нужно. Для вызова `view` нам пришлось указать новую форму возвращаемого тензора. `-1` здесь играет роль «заполнителя», означающего «столько индексов, сколько остается с учетом прочих измерений и исходного количества элементов»

# PreProc some fields

## for one day

In [10]:
first_day = bikes[:24].long()
weather_onehot = torch.zeros(first_day.shape[0], 4)
first_day[:,9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2,
        2, 2])

In [11]:
weather_onehot.scatter_(
    dim=1, 
    index=first_day[:,9].unsqueeze(1).long() - 1, # поскольку погодные условия варьируются от 1 до 4, а индексы начинаются с 0
    value=1.0)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        ...,
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [12]:
torch.cat((bikes[:24], weather_onehot), 1)[:1]

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          6.0000,  0.0000,  1.0000,  0.2400,  0.2879,  0.8100,  0.0000,
          3.0000, 13.0000, 16.0000,  1.0000,  0.0000,  0.0000,  0.0000]])

# делаем то же самое с тензором измененной формы daily_bikes, его форма (B, C, L), где L = 24. 
## Сначала создаем нулевой тензор с теми же B и L, но с числом дополнительных столбцов C

In [13]:
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4,
                                   daily_bikes.shape[2])
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [14]:
daily_weather_onehot.scatter_(
    1, daily_bikes[:,9,:].long().unsqueeze(1) - 1, 1.0)
daily_weather_onehot.shape

torch.Size([730, 4, 24])

## И производим конкатенацию по измерению C

In [15]:
daily_bikes = torch.cat((daily_bikes, daily_weather_onehot), dim=1)

## далее варианты нормализации

In [16]:
daily_bikes[:, 9, :] = (daily_bikes[:, 9, :] - 1.0) / 3.0

In [17]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - temp_min)
                         / (temp_max - temp_min))

In [18]:
temp = daily_bikes[:, 10, :]
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - torch.mean(temp))
                         / torch.std(temp))